spring:
  -main:
    -banner-mode: off

  ####################MySQL Properties##################

  datasource:
    -url: jdbc:mysql://localhost:3306/onlinequizdb?serverTimezone=UTC&autoreconnect = true
    -driver-class-name: com.mysql.cj.jdbc.Driver
    -username: root
    -password: 1111

  ####################JPA Properties####################

  -jpa:
    -properties:
      -hibernate:
        -format_sql: true
    -generate-ddl: true
    -show-sql: true

    ####################Mail Properties####################

  -mail:
    -properties:
      -mail:
        -smtp:
          -connectiontimeout: 5000
          -starttls:
            -enable: true
          -writetimeout: 5000
          -timeout: 5000
          -auth: true
    -username: example@gmail.com
    -host: smtp.gmail.com
    -password: password
    -port: 587

  ####################Secret Key####################

jwt:
  -secret: c21zeXN0ZW1zZWNyZXQ

