-- MySQL Script generated by MySQL Workbench
-- Tue Feb 11 15:44:46 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE =
        'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema OnlineQuizDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema OnlineQuizDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OnlineQuizDB` DEFAULT CHARACTER SET utf8;
USE `OnlineQuizDB`;

-- -----------------------------------------------------
-- Table `OnlineQuizDB`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineQuizDB`.`USER`
(
    `ID`                  BIGINT(20)   NOT NULL,
    `FIRST_NAME`          VARCHAR(255) NULL,
    `LAST_NAME`           VARCHAR(255) NULL,
    `USERNAME`            VARCHAR(255) NOT NULL,
    `PASSWORD`            VARCHAR(255) NOT NULL,
    `EMAIL`               VARCHAR(255) NULL,
    `PHONE_NUMBER`        VARCHAR(255) NULL,
    `GENDER`              TINYINT(1)   NULL,
    `BIRTH_DATE`          BIGINT(20)   NULL,
    `REGISTRATION_STATUS` TINYINT(1)   NULL,
    `STATUS`              TINYINT(1)   NULL,
    `CREATION_DATE`       BIGINT(20)   NULL,
    PRIMARY KEY (`ID`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineQuizDB`.`CONFIRMATION_TOKEN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineQuizDB`.`CONFIRMATION_TOKEN`
(
    `ID`                 BIGINT     NOT NULL,
    `CONFIRMATION_TOKEN` INT        NOT NULL,
    `USER_ID`            BIGINT(20) NOT NULL,
    `CREATION_DATE`      BIGINT(20) NOT NULL,
    PRIMARY KEY (`ID`),
    INDEX `USER_ID_CONFIRMATION_TOKEN_idx` (`USER_ID` ASC) VISIBLE,
    CONSTRAINT `USER_ID_CONFIRMATION_TOKEN`
        FOREIGN KEY (`USER_ID`)
            REFERENCES `OnlineQuizDB`.`USER` (`ID`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineQuizDB`.`AUTHENTICATION_TOKEN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineQuizDB`.`AUTHENTICATION_TOKEN`
(
    `ID`                   BIGINT       NOT NULL,
    `AUTHENTICATION_TOKEN` VARCHAR(255) NOT NULL,
    `USER_ID`              BIGINT(20)   NOT NULL,
    `CREATION_DATE`        BIGINT(20)   NOT NULL,
    PRIMARY KEY (`ID`),
    INDEX `USER_ID_AUTHENTICATION_TOKEN_idx` (`USER_ID` ASC) VISIBLE,
    CONSTRAINT `USER_ID_AUTHENTICATION_TOKEN`
        FOREIGN KEY (`USER_ID`)
            REFERENCES `OnlineQuizDB`.`USER` (`ID`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineQuizDB`.`ROLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineQuizDB`.`ROLE`
(
    `ID`   INT          NOT NULL AUTO_INCREMENT,
    `ROLE` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`ID`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineQuizDB`.`USER_ROLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineQuizDB`.`USER_ROLE`
(
    `USER_ID` BIGINT(20) NOT NULL,
    `ROLE_ID` INT        NOT NULL,
    INDEX `ROLE_ID_USER_ROLE_idx` (`ROLE_ID` ASC) VISIBLE,
    INDEX `USER_ID_USER_ROLE_idx` (`USER_ID` ASC) VISIBLE,
    CONSTRAINT `USER_ID_USER_ROLE`
        FOREIGN KEY (`USER_ID`)
            REFERENCES `OnlineQuizDB`.`USER` (`ID`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `ROLE_ID_USER_ROLE`
        FOREIGN KEY (`ROLE_ID`)
            REFERENCES `OnlineQuizDB`.`ROLE` (`ID`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineQuizDB`.`QUIZ`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineQuizDB`.`QUIZ`
(
    `ID`            BIGINT(20)   NOT NULL AUTO_INCREMENT,
    `NAME`          VARCHAR(255) NOT NULL,
    `TYPE`          TINYINT(1)   NOT NULL,
    `THEME`         TINYINT(1)   NOT NULL,
    `CREATION_DATE` BIGINT(20)   NOT NULL,
    PRIMARY KEY (`ID`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineQuizDB`.`QUESTION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineQuizDB`.`QUESTION`
(
    `ID`            BIGINT(20) NOT NULL,
    `QUESTION`      TEXT(5000) NOT NULL,
    `QUIZ_ID`       BIGINT(20) NOT NULL,
    `CREATION_DATE` BIGINT(20) NOT NULL,
    PRIMARY KEY (`ID`),
    INDEX `QUIZ_ID_QUESTION_idx` (`QUIZ_ID` ASC) VISIBLE,
    CONSTRAINT `QUIZ_ID_QUESTION`
        FOREIGN KEY (`QUIZ_ID`)
            REFERENCES `OnlineQuizDB`.`QUIZ` (`ID`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineQuizDB`.`ANSWER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineQuizDB`.`ANSWER`
(
    `ID`          BIGINT(20) NOT NULL,
    `ANSWER`      TEXT(2000) NOT NULL,
    `SCORE`       INT        NOT NULL,
    `STATUS`      TINYINT(1) NOT NULL,
    `QUESTION_ID` BIGINT(20) NOT NULL,
    `CREATION_ID` BIGINT(20) NOT NULL,
    PRIMARY KEY (`ID`),
    INDEX `QUESTION_ID_ANSWER_idx` (`QUESTION_ID` ASC) VISIBLE,
    CONSTRAINT `QUESTION_ID_ANSWER`
        FOREIGN KEY (`QUESTION_ID`)
            REFERENCES `OnlineQuizDB`.`QUESTION` (`ID`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineQuizDB`.`USER_QUIZ_COMMENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineQuizDB`.`USER_QUIZ_COMMENT`
(
    `ID`            BIGINT(20) NOT NULL,
    `COMMENT`       TEXT(5000) NOT NULL,
    `USER_ID`       BIGINT(20) NOT NULL,
    `QUIZ_ID`       BIGINT(20) NOT NULL,
    `CREATION_DATE` BIGINT(20) NOT NULL,
    PRIMARY KEY (`ID`),
    INDEX `USER_ID_USER_QUIZ_COMMENT_idx` (`USER_ID` ASC) VISIBLE,
    INDEX `QUIZ_ID_USER_QUIZ_COMMENT_idx` (`QUIZ_ID` ASC) VISIBLE,
    CONSTRAINT `USER_ID_USER_QUIZ_COMMENT`
        FOREIGN KEY (`USER_ID`)
            REFERENCES `OnlineQuizDB`.`USER` (`ID`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `QUIZ_ID_USER_QUIZ_COMMENT`
        FOREIGN KEY (`QUIZ_ID`)
            REFERENCES `OnlineQuizDB`.`QUIZ` (`ID`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
